# Generated by Django 4.2.2 on 2023-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=255)),
                ('idea_description', models.CharField(max_length=1000)),
                ('idea_instant_investment', models.IntegerField()),
                ('idea_total_investment', models.IntegerField()),
                ('posted_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
