# Generated by Django 4.2.2 on 2023-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_idea_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_approved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
