# Generated by Django 4.2.2 on 2023-09-15 16:51

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_idea_idea_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=builtins.callable, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
