# Generated by Django 4.2.2 on 2023-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_idea_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_posted_by_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_posted_by_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
