# Generated by Django 4.2.2 on 2023-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_deal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugs_and_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=99999)),
            ],
        ),
    ]
