# Generated by Django 4.2.6 on 2023-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_idea_idea_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='balance',
            field=models.IntegerField(default=399),
        ),
    ]
