# Generated by Django 4.2.6 on 2023-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_agent_call_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs_and_messages',
            name='mail',
            field=models.CharField(max_length=50),
        ),
    ]
